apiVersion: apps/v1
kind: Deployment
metadata:
  name: olatech
  labels:
    app: olatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olatech
  template:
    metadata:
      labels:
        app: olatech
    spec:
      containers:
        - name: olatech
          image: 308134718221.dkr.ecr.us-east-2.amazonaws.com/olatech:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080