apiVersion: apps/v1
kind: Deployment
metadata:
  name: Olatech
  labels:
    app: Olatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Olatech
  template:
    metadata:
      labels:
        app: Olatech
    spec:
      containers:
        - name: Olatech
          image: 308134718221.dkr.ecr.us-east-2.amazonaws.com/primuslearning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080